- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 1800
  startingGear: DoctorGear
  icon: "MedicalDoctor"
  supervisors: job-supervisors-cmo
  setPreference: true
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: UniformScrubsColorBlue
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
