- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 3600 #1 hr
  startingGear: SecurityOfficerGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  setPreference: true
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsMerc
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesMercFingerless
    outerClothing: ClothingOuterVestWeb
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpsuitMercenary
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
