- type: cargoProduct
  id: MissilesT1
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: CrateT1Missiles
  cost: 12000
  category: Security
  group: market

- type: cargoProduct
  id: MissilesT2
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: CrateT2Missiles
  cost: 5000
  category: Security
  group: market

- type: cargoProduct
  id: 20mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate20mmAmmo
  cost: 1000
  category: Security
  group: market

- type: cargoProduct
  id: 53mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate53mmAmmo
  cost: 5000
  category: Security
  group: market

- type: cargoProduct
  id: 80mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate80mmAmmo
  cost: 8000
  category: Security
  group: market

- type: cargoProduct
  id: 105mmAmmoHE
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate105mmAmmoHE
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 120mmAmmoHE
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate120mmAmmoHE
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 140mmAmmoHE
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate140mmAmmoHE
  cost: 30000
  category: Security
  group: market

- type: cargoProduct
  id: 105mmAmmoAP
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate105mmAmmoAP
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 120mmAmmoAP
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate120mmAmmoAP
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 140mmAmmoAP
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate140mmAmmoAP
  cost: 30000
  category: Security
  group: market

- type: cargoProduct
  id: 105mmAmmoPF
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate105mmAmmoPF
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 120mmAmmoPF
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate120mmAmmoPF
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 140mmAmmoPF
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate140mmAmmoPF
  cost: 30000
  category: Security
  group: market
