- type: cargoProduct
  id: MissilesT1
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: CrateT1Missiles
  cost: 12000
  category: Security
  group: market

- type: cargoProduct
  id: MissilesT2
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: CrateT2Missiles
  cost: 5000
  category: Security
  group: market

- type: cargoProduct
  id: 20mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate20mmAmmo
  cost: 1000
  category: Security
  group: market

- type: cargoProduct
  id: 53mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate53mmAmmo
  cost: 5000
  category: Security
  group: market

- type: cargoProduct
  id: 105mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate105mmAmmo
  cost: 10000
  category: Security
  group: market

- type: cargoProduct
  id: 140mmAmmo
  icon:
    sprite: _FTL/Structures/Weapons/silo.rsi
    state: closed
  product: Crate140mmAmmo
  cost: 30000
  category: Security
  group: market
