- type: entity
  parent: BaseStructure
  id: BaseWeaponNaval
  name: base weapon
  abstract: true
  description: Better be careful with whatever the fuck you're doing with this thing.
  placement:
    mode: SnapgridCenter
  components:
    - type: Damageable
      damageContainer: Inorganic
    - type: FTLWeapon
    - type: InteractionOutline
    - type: Clickable
    - type: Transform
      anchored: true
    - type: Destructible
      thresholds:
        - trigger:
            !type:DamageTrigger
            damage: 1000
          behaviors:
            - !type:PlaySoundBehavior
              sound:
                collection: GlassBreak
            - !type:DoActsBehavior
              acts: [ "Destruction" ]
#    - type: UserInterface
#      interfaces:
#        - key: enum.WeaponTargetingUiKey.Key
#          type: WeaponTargetingBoundUserInterface
    - type: DeviceNetwork
      deviceNetId: Wireless
      receiveFrequencyId: BasicDevice
    - type: WirelessNetworkConnection
      range: 200
    - type: DeviceLinkSink
      ports:
        - WeaponInputPort
